### ISSUE TITLE
[RESEARCH] Scene manager implementation

### ISSUE THREAD

**Issue by v0peak00** [GroupThesis2024/Paramedic-Training-Game#14]
### Scope: 
- Design a SceneManager class responsible for managing scene transitions and persistence across scenes.
- Implement an factory to create an instance of SceneManager which allows GameManager and MenuManager use
methods from ISceneManager with loose coupling.

### Tasks:
 - [x] Implement the SceneManager class with factory pattern for scene management.
 - [x] Define the SceneManager interface with methods for loading/unloading scenes.
 - [x] Enhance the level loading methods to load straight to level or main menu for added readability.
 - [x] Implement error handling mechanisms to gracefully handle unexpected scenarios during scene management.
 
### Deliverables:
- SceneManager class with functionality using factory pattern.
- Interface definition for SceneManager.
- Documentation detailing usage and integration with GameManager and MenuManager.
