### ISSUE TITLE
Level Loader -component implementation

### ISSUE THREAD

**Issue by v0peak00** [GroupThesis2024/Paramedic-Training-Game#19]
Design and implement a script that automatically spawns objects (NPC's) at random positions within a area and Vehicle object (Bus) upon scene initialization in Unity.

### Scope:
The script will be responsible for instantiating prefabs or game objects at specific locations within the scene. 

### Tasks (Current State):
- [x] Design a flexible Level Loader script that allows for easy configuration of spawn positions and objects.
- [x] Implement the script to instantiate **simple objects** at predefined positions upon scene initialization.

- [ ] Document usage instructions.

### Additional Considerations @henrysneps :
- The script should be modular and easily configurable to accommodate various scene setups and object types.
- What is the minimum amount of information required from back-end for this component to function?
